calib_management/urls.py
from django.urls import path
from calib_management.views import *

from django.contrib.auth import views as auth_views

app_name = 'calib_management'

urlpatterns = [
    path('', ProbeListView.as_view(), name='probe-list'),
    path('installation-create/', PlaceCreateView.as_view(), name='place-create'),
    path('installations-list/', PlaceListView.as_view(), name='place-list'),
    path('installation-delete/<uuid:pk>/delete/', PlaceDeleteView.as_view(), name='place-delete'),
    path('installation-update/<uuid:pk>/update/', PlaceUpdateView.as_view(), name='place-update'),
    path('probe-create/', ProbeCreateView.as_view(), name='probe-create'),
    path('probe-update/<uuid:pk>/update/', ProbeUpdateView.as_view(), name='probe-update'),
    path('probe-delete/<uuid:pk>/delete/', ProbeDeleteView.as_view(), name='probe-delete'),
    path('probe-detail/<uuid:pk>', ProbeDetailView.as_view(), name='probe-detail'),
    path('add-service/<uuid:pk>/', ServiceCreateView.as_view(), name='add-service'),
    path('service-list/', ServiceListView.as_view(), name='service-list'),
    path('service-delete/<uuid:pk>/delete/', ServiceDeleteView.as_view(), name='service-delete'),
    path('service-update/<uuid:pk>/update/', ServiceUpdateView.as_view(), name='service-update'),
    path('service-detail/<uuid:pk>', ServiceDetailView.as_view(), name='service-detail'),
    path('register/', register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html', success_url=''), name='login'),
    path('user/<int:pk>/update/', UserUpdateView.as_view(), name='user-update'),
    path('user/<int:pk>/', UserDetailView.as_view(), name='user-detail'),
    path('user/password-change/', UserPasswordChangeView.as_view(), name='pass-change'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
]

calibration/urls.py
import profile

from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('calib_management.urls')),

]

templates/base.html
<!DOCTYPE html>

<html lang="en">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta charset="UTF-8">
<div class="body bg-success p-2 text-success-emphasis" style="--bs-bg-opacity: .9;">
<div class="container p-3 mb-2 bg-body-secondary b">

    <head>
        <!--- static -->
        {% load static %}
        <link rel="stylesheet" href="{% static 'style.css' %}">
        <!--- Bootstrap css: --->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
              integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
              crossorigin="anonymous">
        <h2>Lista sond</h2>

        <!--- authentication checking --->
        {% if user.is_authenticated %}
            <a href="{% url 'calib_management:probe-list' %}">
                <button type="button" class="btn btn-primary">Lista sond pomiarowych</button>
            </a>
            <a href="{% url 'calib_management:probe-create' %}">
                <button type="button" class="btn btn-secondary">Dodaj sondę</button>
            </a>
            <a href="{% url 'calib_management:place-list' %}">
                <button type="button" class="btn btn-secondary">Lisa instalacji</button>
            </a>
            <a href="{% url 'calib_management:place-create' %}">
                <button type="button" class="btn btn-secondary">Dodaj instalację</button>
            </a>
            <a href="{% url 'calib_management:service-list' %}">
                <button type="button" class="btn btn-secondary">Lista serwisów</button>
            </a>
            <a href="{% url 'calib_management:user-detail' pk=user.id %}">
                <button type="button" class="btn btn-primary">Szczegóły konta</button>
            </a>
            <a href="{% url 'calib_management:user-update' pk=user.id %}">
                <button class="btn btn-light">Modyfikuj konto</button>
            </a>
            <a href="{% url 'calib_management:logout' %}">
                <button type="button" class="btn btn-warning">Wyloguj</button>
            </a>
        {% else %}
            <!--- if user not authenticated: --->
            <a href="{% url 'calib_management:login' %}">
                <button type="button" class="btn btn-warning">Zaloguj</button>
            </a>
            <a href="{% url 'calib_management:register' %}">
                <button type="button" class="btn btn-warning">Załóż konto</button>
            </a>
            <a href="{% url 'calib_management:probe-list' %}">
                <button type="button" class="btn btn-primary">Lista sond pomiarowych</button>
            </a><title></title>
        {% endif %}

    </head>
<br>
    <!-- loading block content -->


    {% block content %}

    {% endblock %}
</div>

<!--- Bootstrap java: --->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</div>
</html>

templates/installation_create.html
<!--- load base.html --->
{% extends 'base.html' %}
{% block content %}
    <form method="post">{% csrf_token %}
        <div class="table-responsive">
        <table class="table table-bordered table-info">
            {{ form.as_table }}
        </table>
        <input type="submit" value="Stwórz instalację" class="btn btn-success">
        </div>
    </form>
{% endblock %}

templates/installation_delete.html
<!--- load base.html --->
{% extends 'base.html' %}
{% block content %}
<form method="post">{% csrf_token %}
    <p>Czy na pewno chcesz usunąć "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Potwierdź" class="btn btn-danger">
</form>
{% endblock %}

templates/installations_list.html
<!--- load base.html --->
{% extends 'base.html' %}
{% block content %}
    <h2>Instalacje i miejsca</h2>
    <div class="table-responsive">
        <table class="table table-bordered table-success">


            <thead>
            <tr>
                <th>Nazwa</th>
                <th>Akcje</th>
            </tr>
            </thead>
            <tbody>
            {% for place in object_list %}
                <tr>
                    <td>{{ place.name }} </td>
                    <td><a type="button" href="{% url 'calib_management:place-delete' pk=place.id %}">
                        <button class="btn btn-danger">Usuń</button>
                    </a>
                        <a type="button" href="{% url 'calib_management:place-update' pk=place.id %}">
                            <button class="btn btn-light">Modyfikuj</button>
                        </a></td>
                </tr>
                </tbody>

            {% empty %}
                <li>Nie dodano żadnej instalacji.</li>
            {% endfor %}
        </table>
    </div>
{% endblock %}

templates/login.html
<!--- load base.html --->
{% extends 'base.html' %}
{% block content %}
    <head>
        <title>Logowanie</title>
    </head>
    <body>
    <h2>Logowanie</h2>
    <form method="post">
        {% csrf_token %}
        <div class="table-responsive">
            <table class="table table-bordered table-info">
                {{ form.as_table }}
            </table>
        </div>
        <button type="submit" class="btn btn-warning">Zaloguj się</button>
    </form>
    </body>
{% endblock %}

templates/probe_delete.html
<!--- load base.html --->
{% extends 'base.html' %}
{% block content %}
<form method="post">{% csrf_token %}
    <p>Czy na pewno chcesz usunąć "{{ object.name }}"?</p>
    {{ form }}
    <input type="submit" value="Potwierdź" class="btn btn-danger">
</form>
{% endblock %}

templates/probe_detail.html
<!--- load base.html --->
{% extends 'base.html' %}
{% block content %}
    <!--- probe details --->
    <head>
        <title>{{ object.name }} - Szczegóły sondy</title>
    </head>
    <body>
    <table class="table table-bordered table-success">
        <thead>
        <tr>
            <th>Nazwa</th>
            <td>{{ object.name }}</td>
        </tr>
        <tr>
            <th>Numer technologiczny</th>
            <td>{{ object.technology_id }}</td>
        </tr>
        <tr>
            <th>Instalacja</th>
            <td>{{ object.place }}</td>
        </tr>
        <tr>
            <th>Następny serwis do:</th>
            <td>{{ object.get_latest_service.next_service|date:"d.m.Y" }}</td>
        </tr>
        <tr>
            <th>Numer seryjny</th>
            <td>{{ object.serial_number }}</td>
        </tr>
        <tr>
            <th>Producent</th>
            <td>{{ object.factory }}</td>
        </tr>
        <tr>
            <th>Model</th>
            <td>{{ object.probe_model }}</td>
        </tr>
        <tr>
            <th>Data montażu</th>
            <td>{{ object.setup_date|date:"d.m.Y" }}</td>
        </tr>
        <tr>
            <th>Czy sprawna</th>
            <td>
                {% if object.status == True %} Tak
                {% else %}
                    Nie sprawna
                {% endif %}
            </td>
        </tr>
        </thead>
    </table>
    <p>Opis:</p>
    <p>{{ object.description }}</p>
    {% if user.is_authenticated %}
    <a type="button" href="{% url 'calib_management:add-service' pk=object.id %}">
        <button type="button" class="btn btn-secondary" >Dodaj serwis</button>
    </a>
    {% endif %}
    <!--- last service for probe --->
    {% if last_service %}
        <h2>Ostatni serwis</h2>
        <p>Rodzaj obsługi: {{ last_service.name }}</p>
        <p>Data wykonania: {{ last_service.date_time|date:"d.m.Y" }}</p>
        <p>Następna obsługa: {{ last_service.next_service|date:"d.m.Y" }}</p>
    {% endif %}
    </body>
{% endblock %}

templates/probe_list.html
<!--- load base.html --->
{% extends 'base.html' %}
{% block content %}
    <!--- filter for probes in probes list --->
    <h2>Przeszukaj według kryteriów:</h2>
    <div class="table-responsive">
        <form method="get">
            <table class="table table-bordered table-info">
                {{ filter.form.as_table }}
            </table>
            <button type="submit" class="btn btn-info">Wyszukaj</button>
        </form>
    </div>
    {% if filter.qs %}
        <!--- probe list rendering from filter query set --->
        <div class="table-responsive">
        <table class="table table-bordered table-success">
        <thead>
        <tr>
            <th>Nazwa</th>
            <th>Numer technologiczny</th>
            <th>Instalacja</th>
            <th>Następny serwis do:</th>
            <th>Akcje</th>
        </tr>
        </thead>
        <tbody>

        {% for probe in filter.qs %}
            <tr>
                <td>{{ probe.name }}</td>
                <td>{{ probe.technology_id }}</td>
                <td>{{ probe.place }}</td>
                <td>{{ probe.get_latest_service.next_service|date:"d.m.Y" }}</td>
                <td>
                    <a href="{% url 'calib_management:probe-detail' pk=probe.id %}">
                        <button type="button" class="btn btn-primary">Szczegóły</button>
                    </a>
                    {% if user.is_authenticated %}
                        <a type="button" href="{% url 'calib_management:probe-delete' pk=probe.id %}">
                            <button type="button" class="btn btn-danger">Usuń</button>
                        </a>
                        <a type="button" href="{% url 'calib_management:probe-update' pk=probe.id %}">
                            <button type="button" class="btn btn-light">Modyfikuj</button>
                        </a>
                    {% endif %}
                </td>
            </tr>
            <tr>

            </tr>
        {% endfor %}
    {% else %}
        <tr>
            <td colspan="2">Nie dodano żadnej sondy.</td>
        </tr>
    {% endif %}
</tbody>
</table>
</div>

{% endblock %}

templates/probe_update.html
<!--- load base.html --->
{% extends 'base.html' %}
{% block content %}
    <form method="post">{% csrf_token %}
        <div class="table-responsive">
            <table class="table table-bordered table-info">
                {{ form.as_table }}
            </table>
        </div>
        <button type="submit" class="btn btn-success">Zapisz zmiany</button>
    </form>
{% endblock %}

templates/register.html
<!--- load base.html --->
{% extends 'base.html' %}
{% block content %}
    <head>
        <title>Rejestracja</title>
    </head>
    <body>
    <h2>Rejestracja</h2>
    <form method="post">
        {% csrf_token %}
        <div class="table-responsive">
            <table class="table table-bordered table-info">
                {{ form.as_table }}
            </table>
        </div>
        <button type="submit" class="btn btn-warning">Zarejstruj się</button>
    </form>
    </body>
{% endblock %}

templates/service_detail.html
<!--- load base.html --->
{% extends 'base.html' %}
{% block content %}
<head>
    <title>Szczegóły obsługi</title>
</head>
<body>
    <h2>Obsługa: {{ service.name }}</h2>
    <p>Rodzaj obsługi: {{ service.name }}</p>
    <p>Data wykonania: {{ service.date_time }}</p>
    <p>Obsługiwane urządzenie: {{ service.probe }}</p>
    <p>Termin kolejnej obsługi: {{ service.next_service }}</p>
    <p>Opis wykonanych czynności: {{ service.description }}</p>
    <p>Wykonał: {{ service.added_by.last_name }} {{ service.added_by.first_name }}</p>
    <a type="button" href="{% url 'calib_management:service-update' pk=service.id %}">
        <button type="button" class="btn btn-light" >Modyfikuj</button></a>
    <a type="button" href="{% url 'calib_management:service-delete' pk=service.id %}">
        <button type="button" class="btn btn-danger" >Usuń</button></a>
</body>
{% endblock %}

templates/service_list.html
<!--- load base.html --->
{% extends 'base.html' %}
{% block content %}
    <h2>Lista wykonanych czynności</h2>
    <!--- service list filter --->
    <form method="get">
        <table class="table table-bordered table-info">
            {{ filter.form.as_table }}
        </table>
        <button type="submit" class="btn btn-info">Wyszukaj</button>
    </form>

    {% if filter.qs %}
        <div class="table-responsive">
        <table class="table table-bordered table-success">
        <thead>
        <tr>
            <th>Nazwa</th>
            <th>Data serwisu</th>
            <th>Instalacja (miejsce):</th>
            <th>Numer technologiczny</th>
            <th>Następny serwis do</th>
            <th>Wykonał</th>
            <th>Akcje</th>
        </tr>
        </thead>
        <tbody>
        <!--- rendering services from filter query set --->
        {% for service in filter.qs %}
            <tr>
                <td>{{ service.name }}</td>
                <td>{{ service.date_time|date:"d.m.Y" }}</td>
                <td>{{ service.probe.place }}</td>
                <td>{{ service.probe.technology_id }}</td>
                <td>{{ service.next_service|date:"d.m.Y" }}</td>
                <td>{{ service.added_by.last_name }}</td>
                <td>
                    <a href="{% url 'calib_management:service-detail' pk=service.id %}">
                        <button type="button" class="btn btn-primary">Szczegóły</button>
                    </a>
                    <a type="button" href="{% url 'calib_management:service-delete' pk=service.id %}">
                        <button type="button" class="btn btn-danger">Usuń</button>
                    </a>
                    <a type="button" href="{% url 'calib_management:service-update' pk=service.id %}">
                        <button type="button" class="btn btn-light">Modyfikuj</button>
                    </a>

                </td>
            </tr>

        {% endfor %}
    {% else %}
        <tr>
            <td colspan="2">Nie wykonano żadnego serwisu.</td>
        </tr>
    {% endif %}
</tbody>
</table>
</div>



{% endblock %}

templates/user_pass_change.html
<!--- load base.html --->
{% extends 'base.html' %}
{% block content %}
<head>
    <meta charset="UTF-8">
    <title>Zmiana hasła</title>
</head>
<body>
    <h2>Zmiana hasła</h2>
    <form method="post">
        {% csrf_token %}
        <div class="table-responsive">
        <table class="table table-bordered table-info">
        {{ form.as_table }}
        </table>
        </div>
        <button type="submit" class="btn btn-success">Zapisz zmiany</button>
    </form>
</body>
{% endblock %}

templates/user_update.html
<!--- load base.html --->
{% extends 'base.html' %}
{% block content %}
    <head>
        <meta charset="UTF-8">
        <title>Zaktualizuj dane</title>
    </head>
    <body>
    <h2>Zaktualizuj dane</h2>
    <form method="post">
        {% csrf_token %}
        <div class="table-responsive">
            <table class="table table-bordered table-info">
                {{ form.as_table }}
            </table>
        </div>
        <button type="submit" class="btn btn-success">Zapisz zmiany</button>
    </form>
    <a type="button" href="{% url 'calib_management:pass-change' %}">
        <button class="btn btn-danger">Zmień hasło</button>
    </a>
    </body>
{% endblock %}